// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ashqbiyiyylewnkzvobr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzaHFiaXlpeXlsZXdua3p2b2JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDU5MDIsImV4cCI6MjA2MDEyMTkwMn0.kmYhA4eiuDMtn_WOJ4haI8ArvDea2O5_gU7oSwx0KCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);